dist: trusty
sudo: false
language: python

python: "3.6"

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database zenboard;' -U postgres

install:
  - pip install tox-travis

script:
  - tox

before_install:
  - pip install coveralls

after_success:
  - tox -e coverage-report
  - coveralls
