# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 19:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='Name')),
                ('github_repository', models.CharField(help_text="In format: ':owner/:repo'.", max_length=255, verbose_name='GitHub repository')),
                ('github_repository_id', models.CharField(editable=False, max_length=255, verbose_name='GitHub repository ID')),
                ('github_labels', models.CharField(blank=True, help_text='Comma separated list of GitHub labels that will be used to filter issues. If none provided, all issues will be visible.', max_length=255, verbose_name='GitHub labels name')),
                ('filter_sign', models.CharField(default='🐙', max_length=16, verbose_name='filter sign')),
                ('include_epics', models.BooleanField(default=False, verbose_name='include Epic issues')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('whitelisted_users', models.ManyToManyField(blank=True, related_name='boards', to=settings.AUTH_USER_MODEL, verbose_name='whitelisted users')),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
            },
        ),
    ]
